server:
  port: 8070
spring:
  application:
    name: "ReportsApi"
  devtools:
    add-properties: false
logging:
  level:
    org:
      springframework:
        web: "DEBUG"
aws:
  region: "${AWS_REGION}"
  dynamodb:
    endpoint: "${DYNAMO_DB_HOST}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "${CORS}"
routes:
  report:
    paths:
      reports: "/api/v1/report"
jwt:
  secret: "${JWT_SECRET}"
entrypoint:
  sqs:
    region: "${AWS_REGION}"
    queueUrl: "${QUEUE_URL_LISTENER_REPORT}"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
